/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef NOC_ERROR_HWIO_H
#define NOC_ERROR_HWIO_H

#include <stdint.h>
#include <stddef.h>
#include "hal_hwio.h"

/* Base addresses for various NOCs */
#define CONFIG_NOC_CNOC_REG_BASE                         0x00500000UL
#define SYSTEM_NOC_SYSTEM_NOC_REG_BASE                   0x00580000UL
#define AGGR_NOC_AGGR_NOC_REG_BASE                       0x00600000UL
#define GEMNOC_GEMNOC_REG_BASE                           0x04300000UL
#define NSS_NOC_REG_BASE                                 0x01d00000UL
#define TURING_NSP_NOC_REG_BASE                          0x260c0000UL
#define GCC_CLK_CTL_REG_REG_BASE                         0x01800000UL

/* CONFIG NOC CNOC macros */
#define HWIO_CONFIG_NOC_CNOC_ERL_SWID_LOW_ADDR           (CONFIG_NOC_CNOC_REG_BASE + 0x0)
#define HWIO_CONFIG_NOC_CNOC_SBM_SWID_LOW_ADDR           (CONFIG_NOC_CNOC_REG_BASE + 0xd000)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_MAINCTL_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb008)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL0_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb040)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL1_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb048)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL2_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb050)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL3_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb058)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL4_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb060)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL5_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb068)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL6_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb070)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL7_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb078)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL8_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb080)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL9_LOW_ADDR     (CONFIG_NOC_CNOC_REG_BASE + 0xb088)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL10_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb090)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL11_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb098)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL12_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0a0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL13_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0a8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL14_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0b0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL15_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0b8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL16_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0c0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL17_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0c8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL18_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0d0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL19_LOW_ADDR    (CONFIG_NOC_CNOC_REG_BASE + 0xb0d8)

/* GEMNOC macros */
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_SWID_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0xe000)
#define HWIO_GEMNOC_GEMNOC_REFGEN_MAINCTL_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa008)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL0_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa040)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL1_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa048)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL2_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa050)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL3_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa058)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL4_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa060)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL5_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa068)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL6_LOW_ADDR           (GEMNOC_GEMNOC_REG_BASE + 0xa070)
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_ERR_SWID_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x22800)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_ERR_SWID_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x25800)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_ERR_SWID_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x26800)

/* SYSTEM NOC macros */
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_ERL_SWID_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x0)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_SBM_SWID_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x14000)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_REFGEN_MAINCTL_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x6008)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_REFGEN_REFCTL0_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x6040)

/* AGGR NOC macros */
#define HWIO_AGGR_NOC_AGGR_NOC_ERL_SWID_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x0)
#define HWIO_AGGR_NOC_AGGR_NOC_SBM_SWID_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x16000)
#define HWIO_AGGR_NOC_AGGR_NOC_REFGEN_MAINCTL_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c08)
#define HWIO_AGGR_NOC_AGGR_NOC_REFGEN_REFCTL0_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c40)
#define HWIO_AGGR_NOC_AGGR_NOC_REFGEN_REFCTL1_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c48)
#define HWIO_AGGR_NOC_AGGR_NOC_REFGEN_REFCTL2_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c50)
#define HWIO_AGGR_NOC_AGGR_NOC_REFGEN_REFCTL3_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c58)
#define HWIO_AGGR_NOC_AGGR_NOC_REFGEN_REFCTL4_LOW_ADDR \
	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c60)

/* NSS NOC macros */
#define HWIO_NSS_NOC_ERL_SWID_LOW_ADDR                        (NSS_NOC_REG_BASE + 0xa000)
#define HWIO_NSS_NOC_SBM_SWID_LOW_ADDR                        (NSS_NOC_REG_BASE + 0x4000)

/* TURING NSP NOC macros */
#define HWIO_TURING_NSP_NOC_ERL_SWID_LOW_ADDR                 (TURING_NSP_NOC_REG_BASE + 0x0)
#define HWIO_TURING_NSP_NOC_SBM_SWID_LOW_ADDR                 (TURING_NSP_NOC_REG_BASE + 0x200)
#define HWIO_TURING_NSP_NOC_REFGEN_MAINCTL_LOW_ADDR \
	(TURING_NSP_NOC_REG_BASE + 0x408)
#define HWIO_TURING_NSP_NOC_REFGEN_REFCTL0_LOW_ADDR \
	(TURING_NSP_NOC_REG_BASE + 0x440)

/* GEMNOC POC Debug macros */
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_PARAMS_HIGH_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29044)
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_PARAMS_HIGH_NDUMPTMO_BMSK    0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_PARAMS_HIGH_NDUMPTMO_SHFT    16
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_DUMPBRIEF_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29010)
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29038)
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29030)
#define HWIO_GEMNOC_GEMNOC_QNS_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29034)

#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29444)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_NDUMPTMO_BMSK   0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_NDUMPTMO_SHFT   16
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29410)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29438)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29430)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29434)

#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29844)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_NDUMPTMO_BMSK    0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_NDUMPTMO_SHFT    16
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29810)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29838)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29830)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0x29834)

/* GEMNOC FAULT SBM Status macros */
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_ADDR \
	(GEMNOC_GEMNOC_REG_BASE + 0xe048)
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT6_BMSK    0x40
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT6_SHFT    6
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT5_BMSK    0x20
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT5_SHFT    5
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT4_BMSK    0x10
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT4_SHFT    4

/* GCC Clock Control macros */
#define HWIO_GCC_GEMNOC_XO_DBG_CBCR_ADDR                      (GCC_CLK_CTL_REG_REG_BASE + 0x19040)
#define HWIO_GCC_SNOC_XO_DBG_CBCR_ADDR                        (GCC_CLK_CTL_REG_REG_BASE + 0x2e0a0)
#define HWIO_GCC_ANOC0_AXI_CBCR_ADDR                          (GCC_CLK_CTL_REG_REG_BASE + 0x2e0b4)
#define HWIO_GCC_ANOC_XO_DBG_CBCR_ADDR                        (GCC_CLK_CTL_REG_REG_BASE + 0x2e0a4)
#define HWIO_GCC_PCNOC_XO_DBG_CBCR_ADDR                       (GCC_CLK_CTL_REG_REG_BASE + 0x3101c)
#define HWIO_GCC_DDRSS_AHB_CBCR_ADDR                          (GCC_CLK_CTL_REG_REG_BASE + 0x19008)
#define HWIO_GCC_DDRSS_ATB_CBCR_ADDR                          (GCC_CLK_CTL_REG_REG_BASE + 0x19004)
#define HWIO_GCC_NSSCFG_CBCR_ADDR                             (GCC_CLK_CTL_REG_REG_BASE + 0x1702c)
#define HWIO_GCC_NSSNOC_TIMEOUT_REF_CBCR_ADDR                 (GCC_CLK_CTL_REG_REG_BASE + 0x17020)
#define HWIO_GCC_CNOC_TURING_AHBS_CBCR_ADDR                   (GCC_CLK_CTL_REG_REG_BASE + 0x310c0)

#endif /* NOC_ERROR_HWIO_H */
