/*
 * Copyright (c) 2019-2021, The Linux Foundation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/*
 * Changes from Qualcomm Technologies, Inc. are provided under the following license:
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef QTI_SECURE_IO_CFG_H
#define QTI_SECURE_IO_CFG_H

#include <stdint.h>

/*
 * List of peripheral/IO memory areas that are protected from
 * non-secure world but not required to be secure.
 */

#define TCSR_BOOT_MISC_DETECT				0x195C100
#define TCSR_BOOT_INFO					0x195C158
#define APPS_SMMU_STATS_CFG				0x15002584
#define APPS_SMMU_STATS_CB_CFG				0x15002690
#define APPS_SMMU_STATS_CFG_NS				0x15007584
#define APPS_SMMU_STATS_MTLB_LOOKUP_CNTR_NS		0x15007588
#define APPS_SMMU_STATS_WC1_LOOKUP_CNTR_NS		0x15007590
#define APPS_SMMU_STATS_WC2_LOOKUP_CNTR_NS		0x15007594
#define APPS_SMMU_STATS_I0_LOOKUP_CNTR_NS		0x15007598
#define APPS_SMMU_STATS_I1_LOOKUP_CNTR_NS		0x1500759C
#define APPS_SMMU_STATS_I2_LOOKUP_CNTR_NS		0x150075A0
#define APPS_SMMU_STATS_I3_LOOKUP_CNTR_NS		0x150075A4
#define APPS_SMMU_STATS_I4_LOOKUP_CNTR_NS		0x150075A8
#define APPS_SMMU_STATS_MTLB_HIT_CNTR_NS		0x150075AC
#define APPS_SMMU_STATS_PFB_HIT_CNTR_NS			0x150075B0
#define APPS_SMMU_STATS_WC1_HIT_CNTR_NS			0x150075B4
#define APPS_SMMU_STATS_WC2_HIT_CNTR_NS			0x150075B8
#define APPS_SMMU_STATS_I0_HIT_CNTR_NS			0x150075BC
#define APPS_SMMU_STATS_I1_HIT_CNTR_NS			0x150075C0
#define APPS_SMMU_STATS_I2_HIT_CNTR_NS			0x150075C4
#define APPS_SMMU_STATS_I3_HIT_CNTR_NS			0x150075C8
#define APPS_SMMU_STATS_I4_HIT_CNTR_NS			0x150075CC
#define APPS_SMMU_STATS_PTW_CNTR_NS			0x150075D0
#define APPS_SMMU_STATS_PTWQ_2BV4_1BV4_CNTR_NS		0x150075D4
#define APPS_SMMU_STATS_PTWQ_4BV4_3BV4_CNTR_NS		0x150075D8
#define APPS_SMMU_STATS_SYNC_INV_TBU_ACK_NS		0x150075DC
#define APPS_SMMU_STATS_CB_CFG_NS			0x150075E8
#define APPS_SMMU_STATS_2MB_BURST_DEPEND_CNTR_NS	0x150075EC
#define APPS_SMMU_STATS_S1L3_S2L3_WALK_CNTR_NS		0x150075F0
#define APPS_SMMU_STATS_S1L3_S2L3_BURST_CNTR_NS		0x150075F4

static const uintptr_t qti_secure_io_allowed_regs[] = {
	TCSR_BOOT_MISC_DETECT,
	TCSR_BOOT_INFO,
	APPS_SMMU_STATS_CFG,
	APPS_SMMU_STATS_CB_CFG,
	APPS_SMMU_STATS_CFG_NS,
	APPS_SMMU_STATS_MTLB_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_WC1_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_WC2_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_I0_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_I1_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_I2_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_I3_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_I4_LOOKUP_CNTR_NS,
	APPS_SMMU_STATS_MTLB_HIT_CNTR_NS,
	APPS_SMMU_STATS_PFB_HIT_CNTR_NS,
	APPS_SMMU_STATS_WC1_HIT_CNTR_NS,
	APPS_SMMU_STATS_WC2_HIT_CNTR_NS,
	APPS_SMMU_STATS_I0_HIT_CNTR_NS,
	APPS_SMMU_STATS_I1_HIT_CNTR_NS,
	APPS_SMMU_STATS_I2_HIT_CNTR_NS,
	APPS_SMMU_STATS_I3_HIT_CNTR_NS,
	APPS_SMMU_STATS_I4_HIT_CNTR_NS,
	APPS_SMMU_STATS_PTW_CNTR_NS,
	APPS_SMMU_STATS_PTWQ_2BV4_1BV4_CNTR_NS,
	APPS_SMMU_STATS_PTWQ_4BV4_3BV4_CNTR_NS,
	APPS_SMMU_STATS_SYNC_INV_TBU_ACK_NS,
	APPS_SMMU_STATS_CB_CFG_NS,
	APPS_SMMU_STATS_2MB_BURST_DEPEND_CNTR_NS,
	APPS_SMMU_STATS_S1L3_S2L3_WALK_CNTR_NS,
	APPS_SMMU_STATS_S1L3_S2L3_BURST_CNTR_NS
};

#endif /* QTI_SECURE_IO_CFG_H */
