/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef NOC_ERROR_HWIO_USED_H
#define NOC_ERROR_HWIO_USED_H

#include "hal_hwio.h"

/* Base address definitions for NOC */
#define CNOC_WRAPPER_BASE				0x500000
#define SNOC_WRAPPER_BASE				0x580000
#define AGGR_NOC_AGGR_NOC_WRAPPER_BASE			0x600000
#define GEMNOC_WRAPPER_BASE				0x800000
#define CLK_CTL_BASE					0x1800000
#define NSS_PCNOC_REG_BASE				0x1d00000

/* NOC register base definitions */
#define CONFIG_NOC_CNOC_REG_BASE			(CNOC_WRAPPER_BASE + 0x00000000)
#define CONFIG_NOC_CNOC_REG_BASE_SIZE			0x50000
#define CONFIG_NOC_CNOC_REG_BASE_USED			0xb418

#define GEMNOC_GEMNOC_REG_BASE				(GEMNOC_WRAPPER_BASE + 0x002c0000)
#define GEMNOC_GEMNOC_REG_BASE_SIZE			0x13000
#define GEMNOC_GEMNOC_REG_BASE_USED			0x13000

#define SYSTEM_NOC_SYSTEM_NOC_REG_BASE			(SNOC_WRAPPER_BASE + 0x00000000)
#define SYSTEM_NOC_SYSTEM_NOC_REG_BASE_SIZE		0x60000
#define SYSTEM_NOC_SYSTEM_NOC_REG_BASE_USED		0x7d18

#define AGGR_NOC_AGGR_NOC_REG_BASE			(AGGR_NOC_AGGR_NOC_WRAPPER_BASE + 0x00000000)
#define AGGR_NOC_AGGR_NOC_REG_BASE_SIZE			0x11200
#define AGGR_NOC_AGGR_NOC_REG_BASE_USED			0x11134

#define NSS_NOC_REG_BASE				(NSS_PCNOC_REG_BASE + 0x00080000)
#define NSS_NOC_REG_BASE_SIZE				0x10080
#define NSS_NOC_REG_BASE_USED				0x1003c

#define GCC_CLK_CTL_REG_REG_BASE			(CLK_CTL_BASE + 0x00000000)
#define GCC_CLK_CTL_REG_REG_BASE_SIZE			0x40000
#define GCC_CLK_CTL_REG_REG_BASE_USED			0x3f024

/*===========================================================================*/
/*                          CONFIG_NOC_CNOC                                  */
/*===========================================================================*/

/* ERL and SBM */
#define HWIO_CONFIG_NOC_CNOC_ERL_SWID_LOW_ADDR		(CONFIG_NOC_CNOC_REG_BASE + 0x0)
#define HWIO_CONFIG_NOC_CNOC_SBM_SWID_LOW_ADDR		(CONFIG_NOC_CNOC_REG_BASE + 0x1400)

/* REFGEN registers */
#define HWIO_CONFIG_NOC_CNOC_REFGEN_MAINCTL_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb008)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL0_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb040)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL1_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb048)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL2_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb050)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL3_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb058)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL4_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb060)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL5_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb068)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL6_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb070)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL7_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb078)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL8_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb080)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL9_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb088)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL10_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb090)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL11_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb098)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL12_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0a0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL13_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0a8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL14_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0b0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL15_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0b8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL16_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0c0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL17_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0c8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL18_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0d0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL19_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0d8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL20_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0e0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL21_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0e8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL22_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0f0)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL23_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb0f8)
#define HWIO_CONFIG_NOC_CNOC_REFGEN_REFCTL24_LOW_ADDR	(CONFIG_NOC_CNOC_REG_BASE + 0xb100)

/*===========================================================================*/
/*                            SYSTEM_NOC                                     */
/*===========================================================================*/

#define HWIO_SYSTEM_NOC_SYSTEM_NOC_ERL_SWID_LOW_ADDR	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x0)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_SBM_SWID_LOW_ADDR	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x6400)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_REFGEN_MAINCTL_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x6008)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_REFGEN_REFCTL0_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x6040)
#define HWIO_SYSTEM_NOC_SYSTEM_NOC_REFGEN_REFCTL1_LOW_ADDR \
	(SYSTEM_NOC_SYSTEM_NOC_REG_BASE + 0x6048)
/*===========================================================================*/
/*                             AGGR_NOC                                      */
/*===========================================================================*/

#define HWIO_AGGR_NOC_AGGR_NOC_ERL_SWID_LOW_ADDR	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x0)
#define HWIO_AGGR_NOC_AGGR_NOC_SBM_SWID_LOW_ADDR	(AGGR_NOC_AGGR_NOC_REG_BASE + 0x10c00)

/*===========================================================================*/
/*                              GEMNOC                                       */
/*===========================================================================*/

/* SBM and FAULTINSTATUS */
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_SWID_LOW_ADDR			(GEMNOC_GEMNOC_REG_BASE + 0xe000)
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0xe048)
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_RMSK		0x7f
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_INM(m)		\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT6_BMSK	0x40
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT6_SHFT	6
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT5_BMSK	0x20
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT5_SHFT	5
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT4_BMSK	0x10
#define HWIO_GEMNOC_GEMNOC_GEMNOC_FAULT_SBM_FAULTINSTATUS0_LOW_PORT4_SHFT	4

/* REFGEN registers */
#define HWIO_GEMNOC_GEMNOC_REFGEN_MAINCTL_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0xe408)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL0_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0xe440)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL1_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0xe448)
#define HWIO_GEMNOC_GEMNOC_REFGEN_REFCTL2_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0xe450)

/* LLCC POC DBG registers */
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPBRIEF_LOW_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0xfc10)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPBRIEF_LOW_RMSK		0x3ff003f
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPBRIEF_LOW_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPBRIEF_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPBRIEF_LOW_INM(m)		\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPBRIEF_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0xfc30)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_RMSK		0xffffffff
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0xfc34)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_RMSK	0xffffffff
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0xfc38)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_RMSK		0x1
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0xfc44)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_RMSK		0xf0000
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_IN			\
		in_dword(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_ADDR)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_INM(m)		\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_NDUMPTMO_BMSK	0xf0000
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_DBG_PARAMS_HIGH_NDUMPTMO_SHFT	16

/* QNS_PCNOC POC DBG registers */
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10410)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_RMSK	0x3ff003f
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPBRIEF_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10430)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_RMSK	0xffffffff
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_IN	\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10434)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_RMSK	0xffffffff
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_IN	\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10438)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_RMSK	0x1
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_IN	\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_DUMPTMOSTATUS_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0x10444)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_RMSK		0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_NDUMPTMO_BMSK	0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_DBG_PARAMS_HIGH_NDUMPTMO_SHFT	16

/* QNS_PCIE POC DBG registers */
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0x10c10)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_RMSK		0x3ff003f
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPBRIEF_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10c30)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_RMSK	0xffffffff
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_IN	\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10c34)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_RMSK	0xffffffff
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_IN	\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTREAM_HIGH_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x10c38)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_RMSK	0x1
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_IN	\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_INM(m)	\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_DUMPTMOSTATUS_LOW_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0x10c44)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_RMSK		0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_IN		\
		in_dword(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_ADDR)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_INM(m)		\
		in_dword_masked(HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_ADDR, m)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_NDUMPTMO_BMSK	0xf0000
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_DBG_PARAMS_HIGH_NDUMPTMO_SHFT	16

/* POC ERR registers */
#define HWIO_GEMNOC_GEMNOC_LLCC_POC_ERR_SWID_LOW_ADDR		(GEMNOC_GEMNOC_REG_BASE + 0x12400)
#define HWIO_GEMNOC_GEMNOC_QNS_PCNOC_POC_ERR_SWID_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x12800)
#define HWIO_GEMNOC_GEMNOC_QNS_PCIE_POC_ERR_SWID_LOW_ADDR	(GEMNOC_GEMNOC_REG_BASE + 0x12c00)

/*===========================================================================*/
/*                              NSS_NOC                                      */
/*===========================================================================*/

#define HWIO_NSS_NOC_SBM_SWID_LOW_ADDR			(NSS_NOC_REG_BASE + 0x4000)
#define HWIO_NSS_NOC_ERL_SWID_LOW_ADDR			(NSS_NOC_REG_BASE + 0x10000)

/*===========================================================================*/
/*                       GCC Clock Control Registers                        */
/*===========================================================================*/

#define HWIO_GCC_NSSNOC_TIMEOUT_REF_CBCR_ADDR		(GCC_CLK_CTL_REG_REG_BASE + 0x17020)
#define HWIO_GCC_NSSCFG_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x1702c)
#define HWIO_GCC_DDRSS_ATB_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x19004)
#define HWIO_GCC_DDRSS_AHB_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x19008)
#define HWIO_GCC_GEMNOC_XO_DBG_CBCR_ADDR		(GCC_CLK_CTL_REG_REG_BASE + 0x19040)
#define HWIO_GCC_ANOC0_AXI_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x2e078)
#define HWIO_GCC_SNOC_XO_DBG_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x2e0a0)
#define HWIO_GCC_ANOC_XO_DBG_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x2e0a4)
#define HWIO_GCC_PCNOC_XO_DBG_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x3101c)

#endif /* NOC_ERROR_HWIO_USED_H */
