/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef TARGET_HWIO_H
#define TARGET_HWIO_H

/* Base address definitions */
#define GCC_CLK_CTL_REG_REG_BASE			0x01800000
#define TCSR_TCSR_REGS_REG_BASE				0x01917000

/* Clock control register address definitions */
#define HWIO_GCC_SDCC1_AHB_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x3303c)
#define HWIO_GCC_SDCC1_ICE_CORE_CBCR_ADDR		(GCC_CLK_CTL_REG_REG_BASE + 0x33034)
#define HWIO_GCC_QPIC_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE + 0x32028)
#define HWIO_GCC_QPIC_AHB_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE + 0x32010)

/* TCSR ACXPU4 register address definitions */
#define HWIO_TCSR_ACXPU4_GCR_ADDR			(TCSR_TCSR_REGS_REG_BASE + 0x30000)
#define HWIO_TCSR_ACXPU4_GCR_CFGOWNS_BMSK		0x1
#define HWIO_TCSR_ACXPU4_GCR_CFGOWNS_SHFT		0

#define HWIO_TCSR_ACXPU4_DCR_ADDR			(TCSR_TCSR_REGS_REG_BASE + 0x31000)
#define HWIO_TCSR_ACXPU4_DCR_SLE_BMSK			0xf
#define HWIO_TCSR_ACXPU4_DCR_SLE_SHFT			0

#define HWIO_TCSR_ACVIOCR_ADDR				(TCSR_TCSR_REGS_REG_BASE + 0x32000)
#define HWIO_TCSR_ACVIOCR_APSVIOE_BMSK			0x1
#define HWIO_TCSR_ACVIOCR_APSVIOE_SHFT			0
#define HWIO_TCSR_ACVIOCR_OUT(val)			out_dword(HWIO_TCSR_ACVIOCR_ADDR, val)
#define HWIO_TCSR_ACVIOCR_IN				in_dword(HWIO_TCSR_ACVIOCR_ADDR)

/* DDR MPU XPU4 CLERE register definitions
 * In IPQ96xx DDR region is protected by LLCC MPU
 */
#define DDR_MPU_XPU_ID                                  HAL_XPU2_MACHX_LLCC_MPU
#define DDR_MPU_XPU_CLERE_NS_BMSK                       0x40000000

/* TCSR SS XPU4 MALICIOUS INTERRUPT ENABLE register definitions */
#define HWIO_TCSR_XPU_INTR0_ENABLE_ADDR	(TCSR_TCSR_REGS_REG_BASE + 0x23008)
#define HWIO_TCSR_XPU_INTR0_ENABLE_DDR_MPU_IRQ_ENABLE_BMSK  0x80000
#define HWIO_TCSR_XPU_INTR0_ENABLE_DDR_MPU_IRQ_ENABLE_SHFT	19

/* OCIMEM MPU XPU4 CLERE register definitions */
#define OCIMEM_MPU_XPU_ID                                  HAL_XPU2_IMEM_MPU
#define OCIMEM_MPU_XPU_CLERE_NS_BMSK                       0x40000000

/* TCSR SS XPU4 MALICIOUS INTERRUPT ENABLE register definitions */
#define HWIO_TCSR_XPU_INTR0_ENABLE_ADDR	(TCSR_TCSR_REGS_REG_BASE + 0x23008)
#define HWIO_TCSR_XPU_INTR0_ENABLE_OCIMEM_MPU_IRQ_ENABLE_BMSK  0x8000000
#define HWIO_TCSR_XPU_INTR0_ENABLE_OCIMEM_MPU_IRQ_ENABLE_SHFT	27


#endif /* TARGET_HWIO_H */
