/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef _AC_ERROR_CODES_H_
#define _AC_ERROR_CODES_H_

/*--------------------------------------------------------------------------
 * Definitions and Types
 *--------------------------------------------------------------------------
 */
typedef enum {
	AC_SUCCESS                                   = 0,
	AC_FAILURE                                   = 1,
	AC_ERR_INPUT_VALIDATION                      = 2,
	AC_ERR_NOT_LOCKING                           = 3,
	AC_ERR_XPU_NO_FREE_RG                        = 4,
	AC_ERR_NO_DYNAMIC_RG_INFO                    = 5,
	AC_ERR_XPU_RG_NOT_ENABLED                    = 6,
	AC_ERR_XPU_RG_PERM_MISMATCH                  = 7,
	AC_ERR_XPU_RG_ADDR_MISMATCH                  = 8,
	AC_ERR_XPU_RG_WRITE_MISMATCH                 = 9,
	AC_ERR_XPU_RG_WOWP_MISMATCH                  = 10,
	AC_ERR_XPU_APNSPE_ENABLE                     = 11,
	AC_ERR_REGION_ADDR_NOT_ALIGNED               = 12,
	AC_ERR_REGION_SIZE_NOT_ALIGNED               = 13,
	AC_ERR_REGION_SIZE_ZERO                      = 14,
	AC_ERR_REGION_OVERFLOW                       = 15,
	AC_ERR_NULL_POINTER                          = 16,
	AC_ERR_DOMAIN_COUNT_ZERO                     = 17,
	AC_ERR_POINTER_OVERFLOW                      = 18,
	AC_ERR_DOMAIN_INVALID                        = 19,
	AC_ERR_PERM_INVALID                          = 20,
	AC_ERR_DOMAIN_LOCK_INVALID                   = 21,
	AC_ERR_REGION_XPU_NOT_FOUND                  = 22,
	AC_ERR_NO_XPU_INFO                           = 23,
	AC_XPU_CONFIG_NOT_SUPPORTED                  = 24,
	AC_XPU_NO_LOCK_REQUESTED                     = 25,
	AC_XPU_OVERLAP_WITHOUT_ADJACENT              = 26,
	AC_QAD_LOCK_NOT_SUPPORTED                    = 27,
	AC_ERR_XPU_ERROR_REPORTING                   = 28,
	AC_MEMORY_CLEAR_MAP_FAILURE                  = 29,
	AC_MEMORY_CLEAR_FAILURE                      = 30,
	AC_MEMORY_CLEAR_UNMAP_FAILURE                = 31,
	AC_ERR_MAPPING_FAILURE                       = 32,
	AC_SHARED_INFO_FETCH_FAILURE                 = 33,
	AC_SHARED_DATA_INIT_FAILURE                  = 34,
	AC_DATA_CORRUPTION                           = 35,
	AC_ERR_NO_XPU_STATIC_POLICY                  = 36,
	AC_XPU_OVERLAP_INVALID                       = 37,
	AC_ERR_DEBUG_QAD_PROGRAM_FAILURE             = 39,
	AC_ERR_REGION_XPU_BOGUS                      = 40,
	AC_ERR_XPU_RG_NOT_FOUND                      = 41,
	AC_ERR_XPU_CONFIG_APNSPE                     = 42,
	AC_ERR_ENV_QAD_MISMATCH                      = 43,
	AC_LOG_PROFILE_MISMATCH                      = 44,
	AC_LOG_PROFILE_INVALID                       = 45,
	AC_XPU_OVERLAP_CHECK_FAIL                    = 46,
	AC_XPU_DBGAR_PROGRAM_FAIL                    = 47,
	AC_XPU_RG_STILL_ENABLED                      = 48,
	AC_ERR_XPU_XC0_TRIGGER_MISMATCH              = 49,
	AC_ERR_XPU_XC1_TRIGGER_MISMATCH              = 50,
	AC_ERR_XPU_UMRPERM_MISMATCH                  = 51,
	AC_ERR_XPU_CFGOWNER_MISMATCH                 = 52,
	AC_ERR_XPU_XC_IGNORED_MISMATCH               = 53,
	AC_ERR_XPU_XC_STATUS_NOT_SET                 = 54,
	AC_ERR_READ_VECTOR_INVALID                   = 55,
	AC_ERR_WRITE_VECTOR_INVALID                  = 56,
	AC_ERR_LOCK_VECTOR_INVALID                   = 57,
	AC_ERR_NUM_QAD_INVALID                       = 58,
	AC_ERR_VALID_QAD_MISMATCH                    = 59,
	AC_ERR_AC_MAGIC_COOKIE_MISMATCH              = 60,
	AC_ERR_XPU_DISABLED                          = 61,
	AC_ERR_DISABLED_ON_EXT_PARTS                 = 62,
	AC_ERR_XPU_PROTECT_REGION_FAILURE            = 63,
	AC_ERR_XPU_UNLOCK_REGION_FAILURE             = 64,
	AC_ERR_XPU_CONFIGURE_APNSPE_FAILURE          = 65,
	AC_ERR_XPU_ERROR_REPORTING_CTRL_FAILURE      = 66,
	AC_ERR_REGION_UNDERFLOW                      = 67,
	AC_ERR_VMID_FAIL                             = 68,
	AC_ERR_OEM_SPARE_ALREADY_DONE                = 69,
	AC_ERR_OEM_SPARE_GET_ARR_SIZE_FAILED         = 70,
	AC_ERR_OEM_SPARE_GET_ARR_FAILED              = 71,
	AC_ERR_OEM_SPARE_PERM_DATA_INVALID           = 72,
	AC_ERR_OEM_SPARE_REGION_ID_INVALID           = 73,
	AC_ERR_OEM_SPARE_PERM_INVALID                = 74,
	AC_ERR_OEM_SPARE_TME_INVOKE_FAILED           = 75,
	AC_ERR_GET_XPU_REG_ADDR_FAILED               = 76,
	AC_ERR_QB_XPU_DATA_CORRUPTED                 = 77,
	AC_ERR_XPU_CLEAR_APNSPE                      = 78,
	AC_ERR_XBL_CONFIG_ENTRY_TME_INVOKE_FAILED    = 79,
	AC_ERR_XPU_INIT_FAILED                       = 80,
	AC_ERR_XPU_CONFIG_IMAGE_NOT_LOADED           = 81,

} AC_ERROR;

#endif // _AC_ERROR_CODES_H_
