/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef TARGET_HWIO_H
#define TARGET_HWIO_H

#define CLK_CTL_BASE					0x1800000
#define CORE_TOP_CSR_BASE				0x1900000

/* Base address definitions */
#define GCC_CLK_CTL_REG_REG_BASE		(CLK_CTL_BASE+0x00000000)
#define GCC_CLK_CTL_REG_REG_BASE_SIZE		0x40000
#define GCC_CLK_CTL_REG_REG_BASE_USED		0x3f024



#define TCSR_TCSR_REGS_REG_BASE			(CORE_TOP_CSR_BASE	+ 0x00037000)
#define TCSR_TCSR_REGS_REG_BASE_SIZE		0x2a000
#define TCSR_TCSR_REGS_REG_BASE_USED		0x29004

/* Clock control register address definitions */
#define HWIO_GCC_SDCC1_AHB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x3303c)
#define HWIO_GCC_SDCC1_ICE_CORE_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x33034)
#define HWIO_GCC_CNOC_WCSS_AHB_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x310ac)
#define HWIO_GCC_QPIC_CBCR_ADDR					(GCC_CLK_CTL_REG_REG_BASE	+ 0x32028)
#define HWIO_GCC_QPIC_AHB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x32010)

/* Additional clock control registers from AccessControlTzTarget.c */
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_ADDR		(GCC_CLK_CTL_REG_REG_BASE	+ 0xc004)
#define HWIO_GCC_QDSS_CFG_AHB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d068)
#define HWIO_GCC_APSS_ATB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x24034)
#define HWIO_GCC_APSS_DBG_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2402c)
#define HWIO_GCC_APSS_TS_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x24030)
#define HWIO_GCC_QDSS_APB2JTAG_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d05c)
#define HWIO_GCC_QDSS_AT_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d034)
#define HWIO_GCC_QDSS_DAP_AHB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d064)
#define HWIO_GCC_QDSS_STM_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d03c)
#define HWIO_GCC_QDSS_ETR_USB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d060)
#define HWIO_GCC_QDSS_EUD_AT_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d06c)
#define HWIO_GCC_QDSS_TRACECLKIN_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d040)
#define HWIO_GCC_QDSS_TSCTR_DIV16_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d054)
#define HWIO_GCC_QDSS_TSCTR_DIV2_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d044)
#define HWIO_GCC_QDSS_TSCTR_DIV3_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d048)
#define HWIO_GCC_QDSS_TSCTR_DIV4_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d04c)
#define HWIO_GCC_QDSS_TSCTR_DIV8_CBCR_ADDR			(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d050)
#define HWIO_GCC_QDSS_TS_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d078)
#define HWIO_GCC_QDSS_USB_CBCR_ADDR				(GCC_CLK_CTL_REG_REG_BASE	+ 0x2d07c)

/* Clock enable bit definitions */
#define HWIO_GCC_SDCC1_AHB_CBCR_CLK_ENABLE_BMSK		0x1
#define HWIO_GCC_SDCC1_AHB_CBCR_CLK_ENABLE_SHFT		0
#define HWIO_GCC_SDCC1_ICE_CORE_CBCR_CLK_ENABLE_BMSK	0x1
#define HWIO_GCC_SDCC1_ICE_CORE_CBCR_CLK_ENABLE_SHFT	0

/* TZ Clock Branch Enable Vote register field definitions */
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_MPM_AHB_CLK_ENA_BMSK		0x2000
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_MPM_AHB_CLK_ENA_SHFT		13
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_IMEM_AXI_CLK_ENA_BMSK		0x1000
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_IMEM_AXI_CLK_ENA_SHFT		12
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_PRNG_AHB_CLK_ENA_BMSK		0x400
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_PRNG_AHB_CLK_ENA_SHFT		10
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_MSG_RAM_AHB_CLK_ENA_BMSK		0x200
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_MSG_RAM_AHB_CLK_ENA_SHFT		9
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_TLMM_CLK_ENA_BMSK		0x100
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_TLMM_CLK_ENA_SHFT		8
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_TLMM_AHB_CLK_ENA_BMSK		0x80
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_TLMM_AHB_CLK_ENA_SHFT		7
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_GEMNOC_APSS_CLK_ENA_BMSK		0x40
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_GEMNOC_APSS_CLK_ENA_SHFT		6
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_CNOC_APSS_AHB_CLK_ENA_BMSK	0x8
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_CNOC_APSS_AHB_CLK_ENA_SHFT	3
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_APSS_AXI_CLK_ENA_BMSK		0x2
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_APSS_AXI_CLK_ENA_SHFT		1
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_APSS_AHB_CLK_ENA_BMSK		0x1
#define HWIO_GCC_APCS_TZ_CLOCK_BRANCH_ENA_VOTE_APSS_AHB_CLK_ENA_SHFT		0

/* TCSR ACXPU4 register address definitions */
#define HWIO_TCSR_ACXPU4_GCR_ADDR					(TCSR_TCSR_REGS_REG_BASE	+ 0x10000)
#define HWIO_TCSR_ACXPU4_GCR_CFGOWNS_BMSK				0x1
#define HWIO_TCSR_ACXPU4_GCR_CFGOWNS_SHFT				0

#define HWIO_TCSR_ACXPU4_DCR_ADDR					(TCSR_TCSR_REGS_REG_BASE	+ 0x11000)
#define HWIO_TCSR_ACXPU4_DCR_SLE_BMSK					0xf
#define HWIO_TCSR_ACXPU4_DCR_SLE_SHFT					0

#define HWIO_TCSR_ACVIOCR_ADDR						(TCSR_TCSR_REGS_REG_BASE	+ 0x12000)
#define HWIO_TCSR_ACVIOCR_RMSK						0x1
#define HWIO_TCSR_ACVIOCR_IN			\
		in_dword(HWIO_TCSR_ACVIOCR_ADDR)
#define HWIO_TCSR_ACVIOCR_OUT(v)		\
		out_dword(HWIO_TCSR_ACVIOCR_ADDR, v)
#define HWIO_TCSR_ACVIOCR_APSVIOE_BMSK					0x1
#define HWIO_TCSR_ACVIOCR_APSVIOE_SHFT					0

/* DDR MPU XPU4 CLERE register definitions
 * In IPQ96xx DDR region is protected by LLCC MPU
 */
#define DDR_MPU_XPU_ID					HAL_XPU2_MACHX_LLCC_MPU
#define DDR_MPU_XPU_CLERE_NS_BMSK			0x40000000

/* TCSR SS XPU4 MALICIOUS INTERRUPT ENABLE register definitions */
#define HWIO_TCSR_XPU_INTR0_ENABLE_ADDR			(TCSR_TCSR_REGS_REG_BASE + 0x3010)
#define HWIO_TCSR_XPU_INTR0_ENABLE_DDR_MPU_IRQ_ENABLE_BMSK	0x400
#define HWIO_TCSR_XPU_INTR0_ENABLE_DDR_MPU_IRQ_ENABLE_SHFT	10

/* OCIMEM MPU XPU4 CLERE register definitions */
#define OCIMEM_MPU_XPU_ID				HAL_XPU2_IMEM_MPU
#define OCIMEM_MPU_XPU_CLERE_NS_BMSK			0x40000000

/* TCSR SS XPU4 MALICIOUS INTERRUPT ENABLE register definitions */
#define HWIO_TCSR_XPU_INTR0_ENABLE_OCIMEM_MPU_IRQ_ENABLE_BMSK	0x1000
#define HWIO_TCSR_XPU_INTR0_ENABLE_OCIMEM_MPU_IRQ_ENABLE_SHFT	12


#endif /* TARGET_HWIO_H */
